#!/usr/bin/env python

import sys
import os

def file_type(path):
    return os.popen('file -b --mime-type "%s"' % path, 'r').read()

def str_reverse(s):
    rev = ''
    for c in s:
        rev = c + rev
    return rev

class File:
    def __init__(self, path):
        self.path = path
        self.rev = str_reverse(path)
        self.mime_type = file_type(path)

    def __cmp__(self, other):
        # Group by mime type
        if self.mime_type < other.mime_type:
            return -1
        elif self.mime_type > other.mime_type:
            return 1

        # Group by reverse filename
        if self.rev < other.rev:
            return -1
        elif self.rev > other.rev:
            return 1

        # Consider as equal
        return 0

def list_dir(path):
    all_dirs = []
    all_files = []
    for root, dirs, files in os.walk(path):
        all_dirs.extend([os.path.join(root, d) for d in dirs])
        all_files.extend([File(os.path.join(root, f)) for f in files])
    return (all_dirs, all_files)

def list_all(paths):
    all_dirs = []
    all_files = []

    for path in paths:
        dirs, files = list_dir(path)
        all_dirs.extend(dirs)
        all_files.extend(files)

    return (all_dirs, all_files)

def main():
    dirs, files = list_all(sys.argv[1:])

    for d in dirs:
        print d
    files.sort()
    for f in files:
        print f.path

if __name__ == '__main__':
        main()
